name: media_launcher_plugin
description: "A new Flutter plugin project."
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.launcher.media.media_launcher_plugin
        pluginClass: MediaLauncherPlugin
      ios:
        pluginClass: MediaLauncherPlugin