name: media_launcher_plugin
description: "A Flutter plugin to launch and share text messages directly to WhatsApp, Telegram, X (Twitter), or via the system share sheet."
version: 1.0.1
homepage: https://github.com/mustafa-kh-98/media_launcher_plugin.git

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.launcher.media.media_launcher_plugin
        pluginClass: MediaLauncherPlugin
      ios:
        pluginClass: MediaLauncherPlugin